### ISSUE TITLE
9b) Klone GitHub repo og laste opp til GitHub repo.

### ISSUE THREAD

**Issue by wathne** [wathne/dat120-22h#3]
9b) Hver student i gruppa skal klone dette Github repositoryet til sin lokale datamaskin og jobbe i
denne mappa med øvingen. Koden dere skriver i denne øvingen skal lastes opp til Github
repositoryet.

**Comment by wathne** [comment]
Jeg antar at terminalen/kommandolinjen på Windows og Mac er nokså lik som for Linux.
Slik jeg forstår det så har vi to fine måter å bidra med kode til et GitHub repository.

Hvis en er registrert som collaborator:
---------------------------------------
cd ~/Documents/uis/dat120/oving9/workdir
git clone https://github.com/wathne/dat120-22h-g94.git
cd dat120-22h-g94
git status -v
git remote -v
git switch -c din_lokale_branch
touch endringer.txt
git add endringer.txt
git commit
git push origin din_lokale_branch
(Ikke push til main branch.)
(Jeg eller noen andre sjekker og merger dine endringer i din_lokale_branch med main branch.)


Hvis en ikke er registrert som collaborator:
--------------------------------------------
Fork mitt repository på GitHub.
(Du får da en kopi av repo'et som du selv administrerer med din GitHub konto.)
cd ~/Documents/uis/dat120/oving9/workdir
git clone https://github.com/BRUKERNAVN/dat120-22h-g94.git
(Med ditt BRUKERNAVN istedenfor git clone https://github.com/wathne/dat120-22h-g94.git)
cd dat120-22h-g94
git status -v
git remote -v
touch endringer.txt
git add endringer.txt
git commit
git push origin main
(Her går det fint å push til main branch siden dette skal til din egen fork på GitHub.)
Trykk på pull request til mitt repo på GitHub.
(Jeg eller noen andre sjekker og merger dine endringer i din fork med mitt repo.)

**Comment by Johnny78i** [comment]
Hvor er det jeg skal skrive inn git kommandoen? Kommandolinjen min får feilmelding hvis jeg prøver å bruke den

**Comment by wathne** [comment]
Er du på Windows, Mac eller Linux?
Har du installert git? Fungerer "git --help"?
