### ISSUE TITLE
9c) Fordeling av oppgaver.

### ISSUE THREAD

**Issue by wathne** [wathne/dat120-22h#4]
9c) Lag en fordeling av oppgaver til de ulike medlemmene i gruppa. Fordel resten av
deloppgavene i øving 9 slik at alle i gruppa har noen deloppgaver de skal gjøre.

**Comment by wathne** [comment]
Hei. Hvilken deloppgave vil dere begynne med?
Vi kan fordele resten senere.

**Comment by Johnny78i** [comment]
Jeg kan holde på med g-h-i for nå

**Comment by wathne** [comment]
> Jeg kan holde på med g-h-i for nå. Er allerede ferdig med g
Bra :)

**Comment by trymholms** [comment]
Er det sånn at eg ikkje kan jobbe med h, i og j? hadde begynt på det og klarer sikkert å bli ganske ferdig idag med dei. 

kan hoppe over på å begynne med menysystem greiene om det er andre som og er kommet et stykke på funksjonene?

**Comment by Johnny78i** [comment]
> 

Jeg har bare gjort g foreløpig, så du kan ta h og i istedenfor meg, men bare registrer på issuene at du gjør dem da

**Comment by wathne** [comment]
Jeg holder på med menysystemet
